[REF-6265] improve error message when component is already defined
Accidentally I had two component jsons in one dir, so the following
message is not very clear.
Exception: Component already defined!
    Prev comp root: /Users/yakov/PyModelPost/
    Curr comp root: /Users/yakov/PyModelPost/

Now it is:
    Prev comp root: /Users/yakov/PyModelPost/component.json
    Curr comp root: /Users/yakov/PyModelPost/component2.json